version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: |
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
            aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
            aws configure set default.region ap-south-1
      - run:
          name: Copy .env from S3
          command: |
            aws s3 cp s3://aditya-birla/.env .env || echo "Failed to copy .env file from S3" && echo ".env file copied successfully from S3"
            ls -al
            ls -al /path/to
      - run:
          name: Build and push Docker image
          command: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 894185188610.dkr.ecr.ap-south-1.amazonaws.com
            docker build -t 894185188610.dkr.ecr.ap-south-1.amazonaws.com/new-repo:latest .
            docker push 894185188610.dkr.ecr.ap-south-1.amazonaws.com/new-repo:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
