version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: |
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
            aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
            aws configure set default.region ap-south-1
      - run:
          name: Build and push Docker image
          command: |
            SHORT_SHA="${CIRCLE_SHA1::10}.${CIRCLE_BRANCH}"
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 894185188610.dkr.ecr.ap-south-1.amazonaws.com
            docker build -t 894185188610.dkr.ecr.ap-south-1.amazonaws.com/new-repo:$SHORT_SHA .
            docker push 894185188610.dkr.ecr.ap-south-1.amazonaws.com/new-repo:$SHORT_SHA
      - run:
          name: Update ECS service
          command: |
            aws ecs register-task-definition --cli-input-json file://task-definition.json
            aws ecs update-service --cluster newcluster --service newfintechservice --task-definition fintech-centrum:12

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
